# Generated by Django 3.1.2 on 2020-11-17 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Link', models.CharField(max_length=100)),
                ('Author', models.CharField(max_length=100)),
                ('Journal', models.CharField(max_length=100)),
                ('Tag', models.CharField(max_length=100)),
                ('Date', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='result_a',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Link', models.CharField(max_length=1000, unique=True)),
                ('Author', models.CharField(max_length=1000)),
                ('Tag', models.CharField(max_length=100)),
                ('Time', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Trie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_id', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
