# Generated by Django 3.1.2 on 2020-11-19 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_article_journal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Link',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='Tag',
            field=models.CharField(max_length=5000),
        ),
    ]
