# Generated by Django 3.1.2 on 2020-11-23 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20201123_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Tag',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
